/* Generated By:JavaCC: Do not edit this line. parserConstants.java */
package Analyzer.Javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int tPosX = 1;
  /** RegularExpression Id. */
  int tPosY = 2;
  /** RegularExpression Id. */
  int tOpcion = 3;
  /** RegularExpression Id. */
  int tEncuesta = 4;
  /** RegularExpression Id. */
  int tConfiguracion = 5;
  /** RegularExpression Id. */
  int tNumero = 6;
  /** RegularExpression Id. */
  int tIdentificador = 7;
  /** RegularExpression Id. */
  int tLetra = 8;
  /** RegularExpression Id. */
  int tMayorQue = 9;
  /** RegularExpression Id. */
  int tMenorQue = 10;
  /** RegularExpression Id. */
  int tDosPuntos = 11;
  /** RegularExpression Id. */
  int tComa = 12;
  /** RegularExpression Id. */
  int tAmperson = 13;
  /** RegularExpression Id. */
  int tAbreCorchete = 14;
  /** RegularExpression Id. */
  int tCierraCorchete = 15;
  /** RegularExpression Id. */
  int tGuion = 16;
  /** RegularExpression Id. */
  int OTHER = 21;
  /** RegularExpression Id. */
  int inicio = 22;
  /** RegularExpression Id. */
  int cual = 23;
  /** RegularExpression Id. */
  int tString = 24;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int s2 = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"posX\"",
    "\"posY\"",
    "\"_opcion\"",
    "\"_encuesta\"",
    "\"_configuracion\"",
    "<tNumero>",
    "<tIdentificador>",
    "<tLetra>",
    "\">\"",
    "\"<\"",
    "\":\"",
    "\",\"",
    "\"&\"",
    "\"[\"",
    "\"]\"",
    "\"-\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<OTHER>",
    "\"/>\"",
    "<cual>",
    "\"</\"",
  };

}
