/* Generated By:JavaCC: Do not edit this line. parser_calculoConstants.java */
package Analyzer.Javacc_TipoCalculo;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parser_calculoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int tDivision = 1;
  /** RegularExpression Id. */
  int tModulo = 2;
  /** RegularExpression Id. */
  int tPosicion = 3;
  /** RegularExpression Id. */
  int tBoolean = 4;
  /** RegularExpression Id. */
  int tCadMax = 5;
  /** RegularExpression Id. */
  int tCadMin = 6;
  /** RegularExpression Id. */
  int tCadFila = 7;
  /** RegularExpression Id. */
  int tFinalizar = 8;
  /** RegularExpression Id. */
  int tOpcion = 9;
  /** RegularExpression Id. */
  int tSiNO = 10;
  /** RegularExpression Id. */
  int tNumero = 11;
  /** RegularExpression Id. */
  int tDecimal = 12;
  /** RegularExpression Id. */
  int tIdentificador = 13;
  /** RegularExpression Id. */
  int tLetra = 14;
  /** RegularExpression Id. */
  int tFecha = 15;
  /** RegularExpression Id. */
  int tHora = 16;
  /** RegularExpression Id. */
  int tSuma = 17;
  /** RegularExpression Id. */
  int tResta = 18;
  /** RegularExpression Id. */
  int tMultiplicacion = 19;
  /** RegularExpression Id. */
  int tIgual = 20;
  /** RegularExpression Id. */
  int tDiferente = 21;
  /** RegularExpression Id. */
  int tMayorQue = 22;
  /** RegularExpression Id. */
  int tMayorIgualQue = 23;
  /** RegularExpression Id. */
  int tMenorQue = 24;
  /** RegularExpression Id. */
  int tMenorIgualQue = 25;
  /** RegularExpression Id. */
  int tAnd = 26;
  /** RegularExpression Id. */
  int tOr = 27;
  /** RegularExpression Id. */
  int tNot = 28;
  /** RegularExpression Id. */
  int tPunto = 29;
  /** RegularExpression Id. */
  int tDosPuntosSeguidos = 30;
  /** RegularExpression Id. */
  int tArroba = 31;
  /** RegularExpression Id. */
  int tAbreCorchete = 32;
  /** RegularExpression Id. */
  int tCierraCorchete = 33;
  /** RegularExpression Id. */
  int tAbreParent = 34;
  /** RegularExpression Id. */
  int tCierraParent = 35;
  /** RegularExpression Id. */
  int tNumeral = 36;
  /** RegularExpression Id. */
  int tString = 37;
  /** RegularExpression Id. */
  int tString2 = 38;
  /** RegularExpression Id. */
  int tString3 = 39;
  /** RegularExpression Id. */
  int OTHER = 44;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"div\"",
    "\"mod\"",
    "\"posicion\"",
    "<tBoolean>",
    "\"cad_max\"",
    "\"cad_min\"",
    "\"cad_fila\"",
    "\"_finalizar\"",
    "\"_opcion\"",
    "\"si_no\"",
    "<tNumero>",
    "<tDecimal>",
    "<tIdentificador>",
    "<tLetra>",
    "<tFecha>",
    "<tHora>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\".\"",
    "\"..\"",
    "\"@\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"#\"",
    "<tString>",
    "<tString2>",
    "<tString3>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<OTHER>",
  };

}
