/* Generated By:JavaCC: Do not edit this line. parser_expConstants.java */
package Analyzer.Javacc_Exp;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parser_expConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int tDivision = 1;
  /** RegularExpression Id. */
  int tModulo = 2;
  /** RegularExpression Id. */
  int tPosicion = 3;
  /** RegularExpression Id. */
  int tBoolean = 4;
  /** RegularExpression Id. */
  int tNumero = 5;
  /** RegularExpression Id. */
  int tIdentificador = 6;
  /** RegularExpression Id. */
  int tLetra = 7;
  /** RegularExpression Id. */
  int tFecha = 8;
  /** RegularExpression Id. */
  int tHora = 9;
  /** RegularExpression Id. */
  int tSuma = 10;
  /** RegularExpression Id. */
  int tResta = 11;
  /** RegularExpression Id. */
  int tMultiplicacion = 12;
  /** RegularExpression Id. */
  int tIgual = 13;
  /** RegularExpression Id. */
  int tDiferente = 14;
  /** RegularExpression Id. */
  int tMayorQue = 15;
  /** RegularExpression Id. */
  int tMayorIgualQue = 16;
  /** RegularExpression Id. */
  int tMenorQue = 17;
  /** RegularExpression Id. */
  int tMenorIgualQue = 18;
  /** RegularExpression Id. */
  int tAnd = 19;
  /** RegularExpression Id. */
  int tOr = 20;
  /** RegularExpression Id. */
  int tNot = 21;
  /** RegularExpression Id. */
  int tPunto = 22;
  /** RegularExpression Id. */
  int tDosPuntosSeguidos = 23;
  /** RegularExpression Id. */
  int tArroba = 24;
  /** RegularExpression Id. */
  int tAbreCorchete = 25;
  /** RegularExpression Id. */
  int tCierraCorchete = 26;
  /** RegularExpression Id. */
  int tAbreParent = 27;
  /** RegularExpression Id. */
  int tCierraParent = 28;
  /** RegularExpression Id. */
  int tNumeral = 29;
  /** RegularExpression Id. */
  int tString = 30;
  /** RegularExpression Id. */
  int tString2 = 31;
  /** RegularExpression Id. */
  int tString3 = 32;
  /** RegularExpression Id. */
  int OTHER = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"div\"",
    "\"mod\"",
    "\"posicion\"",
    "<tBoolean>",
    "<tNumero>",
    "<tIdentificador>",
    "<tLetra>",
    "<tFecha>",
    "<tHora>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\".\"",
    "\"..\"",
    "\"@\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"#\"",
    "<tString>",
    "<tString2>",
    "<tString3>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<OTHER>",
  };

}
