/* Generated By:JavaCC: Do not edit this line. parserConstants.java */
package Analyzer.Javacc_Exp;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int tNumero = 1;
  /** RegularExpression Id. */
  int tIdentificador = 2;
  /** RegularExpression Id. */
  int tLetra = 3;
  /** RegularExpression Id. */
  int tSuma = 4;
  /** RegularExpression Id. */
  int tResta = 5;
  /** RegularExpression Id. */
  int tMultiplicacion = 6;
  /** RegularExpression Id. */
  int tDivision = 7;
  /** RegularExpression Id. */
  int tModulo = 8;
  /** RegularExpression Id. */
  int tIgual = 9;
  /** RegularExpression Id. */
  int tDiferente = 10;
  /** RegularExpression Id. */
  int tMayorQue = 11;
  /** RegularExpression Id. */
  int tMayorIgualQue = 12;
  /** RegularExpression Id. */
  int tMenorQue = 13;
  /** RegularExpression Id. */
  int tMenorIgualQue = 14;
  /** RegularExpression Id. */
  int tAnd = 15;
  /** RegularExpression Id. */
  int tOr = 16;
  /** RegularExpression Id. */
  int tNot = 17;
  /** RegularExpression Id. */
  int tPunto = 18;
  /** RegularExpression Id. */
  int tDosPuntosSeguidos = 19;
  /** RegularExpression Id. */
  int tArroba = 20;
  /** RegularExpression Id. */
  int tAbreCorchete = 21;
  /** RegularExpression Id. */
  int tCierraCorchete = 22;
  /** RegularExpression Id. */
  int tAbreParent = 23;
  /** RegularExpression Id. */
  int tCierraParent = 24;
  /** RegularExpression Id. */
  int tNumeral = 25;
  /** RegularExpression Id. */
  int OTHER = 30;
  /** RegularExpression Id. */
  int inicio = 31;
  /** RegularExpression Id. */
  int cual = 32;
  /** RegularExpression Id. */
  int tString = 33;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int s2 = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<tNumero>",
    "<tIdentificador>",
    "<tLetra>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"div\"",
    "\"mod\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\".\"",
    "\"..\"",
    "\"@\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"#\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<OTHER>",
    "\"\\\"\"",
    "<cual>",
    "\"\\\"\"",
  };

}
