/* Generated By:JavaCC: Do not edit this line. parserConstants.java */
package Analyzer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMERO = 1;
  /** RegularExpression Id. */
  int IDENTIFIER = 2;
  /** RegularExpression Id. */
  int LETTER = 3;
  /** RegularExpression Id. */
  int tMas = 4;
  /** RegularExpression Id. */
  int tPuntoComa = 5;
  /** RegularExpression Id. */
  int OTHER = 10;
  /** RegularExpression Id. */
  int QUOTED_STRING = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NUMERO>",
    "<IDENTIFIER>",
    "<LETTER>",
    "\"+\"",
    "\";\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<OTHER>",
    "<QUOTED_STRING>",
  };

}
